### ISSUE TITLE
Sorting issue when there's a text before the movie's name

### ISSUE THREAD

**Issue by theghost970** [ssnjr2002/stremio-gdrive#17]
Hi again, ssnjr2002,

I noticed that if there's a text before a movie's name, then it'll get pushed down like shown in the screenshot below. 
It goes like this: 2160p > 1080p > 720p > UnknownRes > 2160pWithTextBeofreMovie'sTitle > 1080pWithTextBeofreMovie'sTitle and so on... 

Not a big deal obviously, but still wanted to let you know.
This is with the latest update btw.

![image](https://user-images.githubusercontent.com/52626961/148344256-192f4766-c27b-4eb1-9b27-dcad2d3187f7.png)

**Comment by ssnjr2002** [comment]
Check now, for some reason the issue got auto closed lol. Reopen if it doesnt work.

**Comment by theghost970** [comment]
> Check now, for some reason the issue got auto closed lol. Reopen if it doesnt work.

No worries lol
I'll check it and report back ,thank you!
BTW, why did you increase the timeout? Was there an issue?

**Comment by ssnjr2002** [comment]
> BTW, why did you increase the timeout? Was there an issue?

Well its more of a safety measure. The default timeout is 30 sec for stremio making a request and the addon giving back a response. Google drive api at max will also take 30 secs to respond. After drive api gives a response, it needs to be processed and that will take 3-4 secs max. So a scenario could arise where drive api takes 30 secs to respond and further 3 secs to process the response, resulting in total of 33 seconds which is over the default timeout of 30 secs and hence the request will timeout. So to prevent that I extended the timeout.

Also in the future I could implement more accurate processing of the results. A few extra seconds would come in handy then.

**Comment by theghost970** [comment]
Makes sense 👍

I was facing an issue where the Stremio becomes heavy and stutters a lot when I play a movie using Cloudflare proxy (Shield TV), so I thought that this was relevant. [It only happens when using the proxy, 15 minutes or so in any movie/show]

And I'm happy to report that the sorting issue has been resolved, thanks!

**Comment by ssnjr2002** [comment]
> I was facing an issue where the Stremio becomes heavy and stutters a lot when I play a movie using Cloudflare proxy (Shield TV), so I thought that this was relevant. [It only happens when using the proxy, 15 minutes or so in any movie/show]

Hmm, not sure why that happens. Open a new issue and keep it there. I will look into it when I got more time.
