### ISSUE TITLE
Heroku Deployment Issue.

### ISSUE THREAD

**Issue by vkazheng** [ssnjr2002/stremio-gdrive#19]
Item could not be created:
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

guess we will have to find other place to deploy this?

**Comment by ssnjr2002** [comment]
See if this works:
- Fork the repo
- Edit readme.md
  - Go to line 57: (`[![Deploy to Heroku](https://www.herokucdn.com/deploy/button.png)](https://heroku.com/deploy?template=https://github.com/ssnjrthegr8/stremio-gdrive.git)`)
  - Change `https://github.com/ssnjrthegr8/stremio-gdrive.git` to `https://github.com/`<YOUR_GITHUB_USERNAME>`/stremio-gdrive.git`
  - Hit save commit
- Now go and click on the deploy button

**Comment by krishne35** [comment]
pushing it to heroku via "connect to github" from heroku works fine too
need to add the variable manually tho

**Comment by aicynide** [comment]
@ssnjr2002 please add kitsu support
