### ISSUE TITLE
Addon doesn't work with latest Stremio Android TV version

### ISSUE THREAD

**Issue by AlyafeiAli** [ssnjr2002/stremio-gdrive#25]
Hi again, ssnjr2002!

I hope you did well in your academics.

If you're not informed, Stremio just released an Android TV version of the app and it looks really great.

However, the gdrive addon is not returning any results in the app for some reason, I can see in the logs that it does find the links and tries to send them back to the Android TV app but nothing shows up in the app.

`10.1.52.7 - - [10/Aug/2022:07:40:27 +0000] "GET /stream/movie/tt5113044.json HTTP/1.1" 200 58784 "-" "-"`

Apparently, it doesn't recognize the Android TV client

**Comment by jaruba** [comment]
we received reports about this too

@ssnjr2002  this addon fails parsing in the new stremio core because  this line: https://github.com/ssnjr2002/stremio-gdrive/blob/27f7de4fb0b52ae2d9b845233d22e1fa30dc777f/sgd/streams.py#L74

which is a string but should be a boolean value

**Comment by AlyafeiAli** [comment]
> which is a string but should be a boolean value
Oh, jaruba himself!
Thank you for the tip, I've corrected the line and it's working now!
And thank you for the amazing job on Stremio

**Comment by jaruba** [comment]
@AlyafeiAli i'm happy it's working!

**Comment by jaruba** [comment]
@AlyafeiAli i think it might be best to leave the issue open until it is fixed in the original repository too, otherwise the developer might not notice it

**Comment by AlyafeiAli** [comment]
> @AlyafeiAli i think it might be best to leave the issue open until it is fixed in the original repository too, otherwise the developer might not notice it

Oh right, good point.
Thanks again :)

**Comment by ssnjr2002** [comment]
Thanks @jaruba for the fix and thanks @AlyafeiAli for bringing the issue to light and testing the fix 👍

**Comment by AlyafeiAli** [comment]
And thank you for the amazing addon, @ssnjr2002 ♥️
